[Definition]

failregex =
    remote-systemd-toggled.*wrong password attempt [0-9]+ from <HOST>
    remote-systemd-toggled.*tls handshake failed from <HOST>:
    remote-systemd-toggled.*client certificate missing from <HOST>
    remote-systemd-toggled.*client certificate CN mismatch from <HOST>:
    remote-systemd-toggled.*read failed from <HOST>:

ignoreregex =
