name: Test

on:
  push:
  pull_request:
  workflow_call:

permissions:
  contents: read

jobs:
  test:
    name: go test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Go
        uses: actions/setup-go@v7
        with:
          go-version-file: go.work
          cache: true

      - name: Run tests
        shell: sh
        run: |
          go list -f '{{.Dir}}' -m | while IFS= read -r dir; do
            (cd "$dir" && go test -v ./...)
          done
