name: Vet

on:
  push:
  pull_request:
  workflow_call:

permissions:
  contents: read

jobs:
  vet:
    name: go vet
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.work
          cache: true

      - name: Run go vet
        shell: sh
        run: |
          go list -f '{{.Dir}}' -m | while IFS= read -r dir; do
            (cd "$dir" && go vet ./...)
          done
